[project]
name = "synthbold"
version = "0.1.0"
description = "Synthetic fMRI generator for BOLD simulations."
authors = [
    { name = "Daniel Haenelt", email = "daniel.haenelt@gmail.com" }
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "monai>=1.5.2",
    "nibabel>=5.4.2",
    "numpy>=2.4.4",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
    "scikit-image>=0.26.0",
    "torch>=2.11.0",
    "types-pyyaml>=6.0.12.20260408",
    "zarr>=3.1.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mypy>=1.20.2",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-sugar>=1.1.1",
    "ruff>=0.15.12",
    "types-pyyaml>=6.0.12.20260408",
]
docs = [
    "autodoc-pydantic>=2.2.0",
    "furo>=2025.12.19",
    "sphinx>=9.1.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
ignore_missing_imports = true  # ignore missing type hints in third-party libraries
disallow_untyped_defs = true   # require functions to have type hints
strict_optional = true         # enforce proper handling of None

[tool.ruff]
line-length = 88
target-version = "py313"
fix = true

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors (flake8)
  "F",   # pyflakes (flake8)
  "I",   # isort
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
]

ignore = [
  "E203", # compatible with black
  "E266",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

# ----------------------------------------------------------
# Backend: uv uses hatchling for build by default
# ----------------------------------------------------------
[project.scripts]
synthbold = "synthbold.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
